### PR TITLE
#47: computeChildrenSize in didMount/update can cause React stack overflows (closes #47)

### LINKED ISSUE #47: computeChildrenSize in didMount/update can cause React stack overflows
We received a few reports of [React error 185](https://reactjs.org/docs/error-decoder.html/?invariant=185). They seem to be related to the interaction between this component code and flexbox layout incremental resizing.
Since this component (`computeChildrenSize` function in particular) is appearing in the stack traces, let's try to be more defensive

### PR DESCRIPTION
**Pull request by giogonzo**
Closes [#2520612](https://buildo.kaiten.io/space/32111/card/2520612)

⚠️ The line above was added during the automatic migration of all github project issues to Kaiten. The old GH issue link is kept here for reference (it is now deprecated, continue follow the original issue on Kaiten).

Closes #47

Didn't really test "the fix", because I wasn't able to reproduce the original issue properly.
The behavior of this component (correctly measuring children and adding internal padding to the input) looks perfectly preserved in the average cases that I tested.

_Note: even if unrelated, this PR also removes runtime React `PropTypes` checking, as we recently did for many other react components_

### CODE REVIEW

File: src/InputChildren.tsx [hunk 1]
```diff
@@ -95,7 +86,7 @@ export class InputChildren extends React.Component<InputChildren.Props, State> {
   }
 
   componentDidUpdate() {
-    this.computeChildrenSize();
+    setTimeout(this.computeChildrenSize);
```
Comment (Cardu) [inline src/InputChildren.tsx]: following react guidelines: https://it.reactjs.org/docs/react-component.html
change state should be called immediately in `componentDidUpdate` and we should add a guard that checks if props are really changed

**Review by Cardu — COMMENTED** [review]
see inline comment

File: src/InputChildren.tsx (hunk 1 above)
Comment (giogonzo) [reply src/InputChildren.tsx]: the check is already there (in `computeChildrenSize`), but not enough apparently 🤷‍♂

Comment (Cardu) [reply src/InputChildren.tsx]: inside computeChildrenSize we are checking props against current state, not against previous props, right?

plus, I fear that setTimeout here could be dangerous because it postpones at next cycle the setState

Comment (giogonzo) [reply src/InputChildren.tsx]: we are not checking props, we are reading directly from the DOM (`clientWidth` and `clientHeight`) and comparing against `state`

I'm not saying I'm a fan of `setTimeout`, but I don't have better ideas 😂 

One thing I can improve is guarding that setState to run only when the component is mounted. I just pushed a commit to do this

**Review by Cardu — APPROVED** [review]
🤞
